### ISSUE TITLE
Lot of debug log messages are coming from carousel view

### ISSUE THREAD

**Issue by RaghavendhraK** [gtomato/carouselview#3]
Hi,

There are lots of debug log messages are coming from the carousel view. Could you please remove the debug log messages, or give the option to hide or enable the logs from the carousel view.

Thanks,
Raghu

**Comment by sunny-chung** [comment]
Hi! Here is the option - `CarouselView.setDebug(false);`.

I will update the library to disable debug logs by default. The default is wrong now.

**Comment by sunny-chung** [comment]
Fixed in v2.0.1.
